# ssh -L 3306:localhost:3306 mars_temporence
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/temporence_dev
    username: admin
    password: Qwer1595@!


#spring:
#  datasource:
#    url: jdbc:mysql://3.212.188.144:3306/mars
#    username: mars
#    password: d~JU8Z4Jv$t"SypX