name: Run Shell File

on:
  push:
    branches:
      - develop

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize Known Hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan 43.200.204.186 >> ~/.ssh/known_hosts
      - name: Set Permissions for Private Key
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > $HOME/key.pem
          chmod 400 $HOME/key.pem
      - name: Run shell script
        run: sh git-dev-deploy.sh
        env:
          SSH_PEM_KEY: ${{ secrets.DEPLOY_SSH_KEY }}