name: Run Shell File

on:
  push:
    branches:
      - develop

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run shell script
        run: sh git-dev-deploy.sh
