name: Run Docker Compose

on:
  push:
    branches:
      - develop

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize Known Hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.EC2_HOST_DEV }} >> ~/.ssh/known_hosts

      - name: Set Permissions for Private Key
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > $HOME/key.pem
          chmod 400 $HOME/key.pem

      - name: Build Docker image
        run: docker build --platform linux/arm64/v8 --build-arg DEPENDENCY=build/dependency --no-cache --rm -f Dockerfile -t pinomaker/mars-game:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub (optional)
        run: docker push pinomaker/mars-game:latest

      - name: Copy files to EC2 instance
        run: |
          scp -i $HOME/key.pem ./docker-compose.yml ubuntu@${{ secrets.EC2_HOST_DEV }}:/home/ubuntu/
          scp -i $HOME/key.pem ./Dockerfile ubuntu@${{ secrets.EC2_HOST_DEV }}:/home/ubuntu/
          scp -i $HOME/key.pem ./.dockerignore ubuntu@${{ secrets.EC2_HOST_DEV }}:/home/ubuntu/

      - name: Run Docker Compose
        env:
          SSH_PEM_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          ssh -i $HOME/key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST_DEV }} "cd /home/ubuntu && docker-compose up -d"


#name: Deploy
#
#on:
#  push:
#    branches:
#      - develop
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Build Docker image
#        run: docker build --build-arg DEPENDENCY=build/dependency --no-cache --rm -f Dockerfile -t pinomaker/mars-game:latest .
#
#      - name: Log in to Docker Hub
#        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Push Docker image to Docker Hub (optional)
#        run: docker push pinomaker/mars-game:latest
#
#      - name: Initialize Known Hosts
#        run: |
#          mkdir -p ~/.ssh
#          touch ~/.ssh/known_hosts
#          ssh-keyscan ${{ secrets.EC2_HOST_DEV }} >> ~/.ssh/known_hosts
#
#      - name: Set Permissions for Private Key
#        run: |
#          echo "${{ secrets.DEPLOY_SSH_KEY }}" > $HOME/key.pem
#          chmod 400 $HOME/key.pem
#        env:
#          SSH_PEM_KEY : ${{ secrets.DEPLOY_SSH_KEY }}
#
#      - name: Deploy to EC2
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.EC2_HOST_DEV }}
#          username: ${{ secrets.EC2_USERNAME_DEV }}
#          key: $HOME/key.pem
#          source: .
#          target: /home/ubuntu
#
#      - name: SSH into EC2 and start the application
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_HOST_DEV }}
#          username: ${{ secrets.EC2_USERNAME_DEV }}
#          key: $HOME/key.pem
#          script: |
#            cd /home/ubuntu
#            docker-compose up -d
