name: Run Shell File

on:
  push:
    branches:
      - develop

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run shell script
        run: |
          echo "gradle build -x test"
          sudo gradle build -x test

          REPOSITORY=/home/ubuntu/temp/ourmindmaze-api
          sudo scp -o StrictHostKeyChecking=no -i seoul.pem ubuntu@43.200.204.186 ./build/libs/ourmindmaze-0.0.1-SNAPSHOT.jar ubuntu@43.200.204.186:$REPOSITORY/build/libs/

          echo "deploy on dev server"
          sudo ssh -o StrictHostKeyChecking=no  -i seoul.pem ubuntu@43.200.204.186 "bash -s" < ./run-server.sh

          echo "Done"
          sudo gradle clean
